-- ============================================================================
-- Seed — School of ICT course catalogue (187 courses)
--
-- Source: Griffith University's official course reading-list directory for the
-- School of Information and Communication Technology
-- (griffith.rl.talis.com/schools/ict), retrieved September 2026.
-- Campus and teaching-period variants (_M2, _P1, ...) collapsed to base codes.
--
-- Idempotent: safe to re-run. Titles are refreshed on conflict.
-- ============================================================================

insert into public.courses (code, title) values
  ('1001ICT', 'Introduction to Programming'),
  ('1004ICT', 'Professional Practice in Information Technology'),
  ('1005ICT', 'Object Oriented Programming'),
  ('1007ICT', 'Computer Systems and Cyber Security'),
  ('1008ICT', 'Business Informatics'),
  ('1011ICT', 'Applied Computing'),
  ('1013ICT', 'Mathematics for Computer Science'),
  ('1116ICT', 'Introduction to AI and Data Analytics'),
  ('1117ICT', 'Big Data Analytics and Social Media'),
  ('1118ICT', 'Fundamentals of Cyber Security'),
  ('1611ICT', 'Emerging Technologies'),
  ('1621ICT', 'Web Technologies'),
  ('1701ICT', 'Creative Coding'),
  ('1711ICT', 'Introduction to Robotics'),
  ('1801ICT', 'Object-Oriented Programming'),
  ('1802ICT', 'Foundations of Systems Development'),
  ('1803ICT', 'Information Systems Foundations'),
  ('1804ICT', 'Data Management'),
  ('1805ICT', 'Human Computer Interaction'),
  ('1806ICT', 'Programming Fundamentals'),
  ('1807ICT', 'Computer and Network Architecture'),
  ('1808ICT', 'Discrete Structures'),
  ('1810ICT', 'Software Development Processes'),
  ('1811ICT', 'Programming Principles'),
  ('1812ICT', 'Data Management'),
  ('1814ICT', 'Data Management'),
  ('2006ICT', 'Object Oriented Software Development'),
  ('2007ICT', 'Cyber Security Standards and Operations'),
  ('2008ICT', 'Design Thinking in IT'),
  ('2016ICT', 'Cloud Architecture and Administration'),
  ('2030ICT', 'Introduction to Big Data Analytics'),
  ('2031ICT', 'Data Analytics Methods'),
  ('2105ICT', 'Advanced Research Project in Information Technology A'),
  ('2420ICT', 'Systems Programming'),
  ('2511ICT', 'Business Analysis'),
  ('2701ICT', 'Interactive App Development'),
  ('2702ICT', 'Intelligent Media Systems'),
  ('2703ICT', 'Web Application Development'),
  ('2800ICT', 'Object Oriented Programming'),
  ('2801ICT', 'Computing Algorithms'),
  ('2802ICT', 'Intelligent Systems'),
  ('2803ICT', 'Systems and Distributed Computing'),
  ('2805ICT', 'System and Software Design'),
  ('2806ICT', 'IT Services Management'),
  ('2807ICT', 'Programming Principles'),
  ('2808ICT', 'Secure Development Operations'),
  ('2809ICT', 'Computer Networking Essentials'),
  ('2810ICT', 'Software Technologies'),
  ('2811ICT', 'Web Programming'),
  ('2812ICT', 'Perceptual Computing'),
  ('2813ICT', 'Software Engineering Fundamentals'),
  ('2814ICT', 'Data Management'),
  ('2815ICT', 'Theory of Computing'),
  ('2905ICT', 'Fundamentals of Cyber Security'),
  ('3001ICT', 'Enterprise Routing and Network Architectures'),
  ('3002ICT', 'Industry Project'),
  ('3003ICT', 'Programming for Robotics'),
  ('3004ICT', 'Web Application Development'),
  ('3005ICT', 'Distributed Programming'),
  ('3006ICT', 'Robotics and Computer Vision'),
  ('3008ICT', 'Deep Learning'),
  ('3009ICT', 'Data Processing and Visualisation'),
  ('3010ICT', 'Cyber Security of Cyber Physical Systems'),
  ('3012ICT', 'Cryptography'),
  ('3014ICT', 'Cyber Security Defence and Incident Response'),
  ('3015ICT', 'Trustworthy AI'),
  ('3016ICT', 'Secure Development Operations'),
  ('3020ICT', 'Industry Affiliates Program'),
  ('3030ICT', 'Data Analytics'),
  ('3031ICT', 'Applied Data Mining'),
  ('3032ICT', 'Big Data Analytics and Social Media'),
  ('3105ICT', 'Advanced Research Project in Information Technology B'),
  ('3301ICT', 'Enterprise Architecture Concepts'),
  ('3407ICT', 'Graphics Programming'),
  ('3410ICT', 'The Ethical Technologist'),
  ('3412ICT', 'Software Architecture'),
  ('3413ICT', 'Network Security'),
  ('3418ICT', 'Strategic IS Management'),
  ('3420ICT', 'Systems Programming'),
  ('3421ICT', 'Multiagent Systems'),
  ('3530ICT', 'Scientific and Parallel Computing'),
  ('3601ICT', 'Professional Practice Portfolio'),
  ('3612ICT', 'Database Systems and Administration'),
  ('3623ICT', 'Information and Content Management'),
  ('3624ICT', '3D Game Development'),
  ('3701ICT', 'Mobile Application Development'),
  ('3702ICT', 'Games Development'),
  ('3705ICT', 'Virtual and Augmented Reality'),
  ('3706ICT', 'Sensor Networks'),
  ('3707ICT', 'Automation and IoT'),
  ('3723ICT', 'Interaction Design'),
  ('3801ICT', 'Numerical Algorithms'),
  ('3802ICT', 'Programming Languages'),
  ('3803ICT', 'Big Data Analysis'),
  ('3804ICT', 'Data Mining'),
  ('3805ICT', 'Advanced Algorithms'),
  ('3806ICT', 'Logic and Automated Reasoning'),
  ('3807ICT', 'IT/Business Alignment'),
  ('3808ICT', 'Routing and Internetworking'),
  ('3809ICT', 'Ethical Hacking'),
  ('3810ICT', 'Enterprise Architecture Application'),
  ('3811ICT', 'Advanced Network Architectures'),
  ('3812ICT', 'Agile Methodologies'),
  ('3813ICT', 'Full Stack Development'),
  ('3815ICT', 'Software Engineering'),
  ('3821ICT', 'Work Integrated Learning - Single Project'),
  ('3822ICT', 'Work Integrated Learning - Placement'),
  ('3825ICT', 'Theory of Computation'),
  ('3906ICT', 'Digital Forensics'),
  ('4030ICT', 'Big Data Analytics and Social Media'),
  ('6001ICT', 'Advanced Topics in Computer Science A'),
  ('6002ICT', 'Advanced Topics in Computer Science B'),
  ('6003ICT', 'Advanced Topics in Computer Science C'),
  ('6004ICT', 'Advanced Topics in Computer Science D'),
  ('6005ICT', 'Research Practice in ICT 1'),
  ('6006ICT', 'Research Practice in ICT 2'),
  ('6105ICT', 'Advanced Topics in Information Technology C'),
  ('6106ICT', 'Advanced Topics in Information Technology D'),
  ('6112ICT', 'Research Methods in IT'),
  ('6190ICT', 'Honours Thesis'),
  ('6205ICT', 'Advanced Topics in Information Technology A'),
  ('6206ICT', 'Advanced Topics in Information Technology B'),
  ('7001ICT', 'Programming Principles'),
  ('7002ICT', 'Systems Development'),
  ('7003ICT', 'Database Design'),
  ('7004ICT', 'Data Communication'),
  ('7005ICT', 'Web Programming'),
  ('7006ICT', 'Introduction to Artificial Intelligence'),
  ('7008ICT', 'Data Processing and Visualisation'),
  ('7009ICT', 'Advances in XR Development'),
  ('7010ICT', 'Object Oriented Software Development'),
  ('7011ICT', 'Data Structures and Algorithms'),
  ('7013ICT', 'Advanced Topics in IT'),
  ('7015ICT', 'Cyber Security Operations Centres'),
  ('7016ICT', 'Cyber Security of Critical Infrastructure'),
  ('7017ICT', 'Responsible and Secure Artificial Intelligence'),
  ('7018ICT', 'Cloud Architecture and Administration'),
  ('7019ICT', 'Cyber Security Risk Management'),
  ('7022ICT', 'Computational Intelligence'),
  ('7030ICT', 'Introduction to Big Data Analytics'),
  ('7031ICT', 'Applied Data Mining'),
  ('7101ICT', 'The Ethical Technologist'),
  ('7103ICT', 'Business Analysis'),
  ('7113ICT', 'Research for IT Professionals'),
  ('7130ICT', 'Data Analytics'),
  ('7204ICT', 'Database Technology'),
  ('7230ICT', 'Big Data Analytics and Social Media'),
  ('7301ICT', 'Enterprise Architecture Concepts'),
  ('7302ICT', 'Enterprise Architecture Applications'),
  ('7401ICT', 'eService Technology'),
  ('7412ICT', 'Software Architecture'),
  ('7418ICT', 'Strategic Information Systems Management'),
  ('7420ICT', 'Advanced Software Development'),
  ('7421ICT', 'Mobile Device Software Development'),
  ('7502ICT', 'Advanced Networking'),
  ('7504ICT', 'Network and Information Security'),
  ('7506ICT', 'Industrial Applications of Blockchain'),
  ('7590ICT', 'Dissertation'),
  ('7610ICT', 'Application Systems'),
  ('7611ICT', 'Computer Systems and Cyber Security'),
  ('7623ICT', 'Secure Development Operations'),
  ('7701ICT', 'IT Project'),
  ('7720ICT', 'Industry Affiliates Program'),
  ('7740ICT', 'Industry Affiliates Program'),
  ('7805ICT', 'System and Software Design'),
  ('7806ICT', 'IT Services Management'),
  ('7807ICT', 'IT/Business Alignment'),
  ('7808ICT', 'Project and Cyber Security Management'),
  ('7809ICT', 'Offensive Cyber Security'),
  ('7810ICT', 'Software Technologies'),
  ('7812ICT', 'Agile Business Analysis'),
  ('7821ICT', 'Work Integrated Learning - Single Project'),
  ('7822ICT', 'Work Integrated Learning - Placement'),
  ('7905ICT', 'Fundamentals of Cyber Security'),
  ('7906ICT', 'Digital Investigations'),
  ('7907ICT', 'IT and Cyber Security Governance, Policy, Ethics and Law'),
  ('7980ICT', 'Cyber Security Capstone Project'),
  ('7990ICT', 'Designing Application Systems and Databases'),
  ('7991ICT', 'Computer Systems and Programming'),
  ('7992ICT', 'Artificial Intelligence and IT Governance'),
  ('7993ICT', 'Network Infrastructure and Cloud Systems'),
  ('7994ICT', 'Security Essentials and Adversarial Techniques'),
  ('7995ICT', 'Data Wrangling and Social Analytics'),
  ('7996ICT', 'Intelligent Systems and Data Analysis'),
  ('7997ICT', 'Capstone Project'),
  ('7998ICT', 'Security Operations Centre and AI'),
  ('7999ICT', 'Critical Infrastructure and Distributed Technologies')

-- Refresh titles if the catalogue has been updated upstream.
on conflict (code) do update set title = excluded.title;
